# Generated by Django 5.0.7 on 2024-08-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_galleryimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
