# Generated by Django 5.0.7 on 2024-08-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_galleryimage_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
